apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-database
spec:
  selector:
    app: ecommerce-database
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-database
spec:
  selector:
    matchLabels:
      app: ecommerce-database
  template:
    metadata:
      labels:
        app: ecommerce-database
    spec:
      containers:
        - name: ecommerce-database
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /data/db
          env:
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_USER
              value: postgres

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: ecommerce-database
