apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
spec:
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          image: ebuozturk/ecommerce-user-server
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:9999
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://ecommerce-database:5432/ecommerce_user

---
apiVersion: v1
kind: Service
metadata:
  name: user-server
spec:
  selector:
    app: user-server
  ports:
    - port: 8081
      targetPort: 8081
