spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ebuozturk/ecommerce-config-server.git
          default-label: main
  application:
    name: config-server
  boot:
    admin:
      client:
        url: http://localhost:8085
server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always